ASSOCIATIONS_FILE: https://file path
graphql:
  playground:
    enabled: true
  servlet:
    enabled: true
    mapping: /graphql
    cors-enabled: true
    cors:
      allowed-origins:
        - "*"
      allowed-methods:
        - "GET"
        - "HEAD"
        - "POST"
      allowed-headers:
        - "*"
    exception-handlers-enabled: true
    context-setting: PER_REQUEST_WITH_INSTRUMENTATION
    async-mode-enabled: true