ASSOCIATIONS_FILE: https://storage.googleapis.com/associations_ot_remo/associations.json
server:
  port: 8090
  errors:
    include-message: always
    include-binding-errors: always

logging:
  level:
    org:
      hibernate:SQL: debug

springdoc:
  swagger-ui.path: /swagger-ui.html